# Generated by Django 6.0.3 on 2026-04-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('university', 'جامعة'), ('high_school', 'ثانوي')], max_length=20, null=True, verbose_name='مرحلة الاجتماع'),
        ),
    ]
