# Generated by Django 6.0.3 on 2026-04-05 17:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfessionAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('attended', models.BooleanField(default=False, verbose_name='حضر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confession_attendances', to=settings.AUTH_USER_MODEL, verbose_name='المخدوم')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_confession_attendances', to=settings.AUTH_USER_MODEL, verbose_name='سُجل بواسطة')),
            ],
            options={
                'verbose_name': 'حضور اعتراف',
                'verbose_name_plural': 'سجلات حضور الاعترافات',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['member', 'date'], name='confessions_member__a2c0cc_idx')],
                'unique_together': {('member', 'date')},
            },
        ),
    ]
